# Generated by Django 5.2.10 on 2026-01-29 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InputDataSnapshot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "data_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Data ID (Snapshot Key)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Base Year Month",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Input Data Snapshot",
                "verbose_name_plural": "Input Data Snapshot",
                "db_table": "cas_input_data_snapshot",
            },
        ),
        migrations.CreateModel(
            name="GreenhouseGasTarget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "greenhouse_gas_target_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "ghg_target_effective_from_year",
                    models.CharField(
                        max_length=4, verbose_name="GHG Target Effective From Year"
                    ),
                ),
                (
                    "ghg_target_effective_to_year",
                    models.CharField(
                        max_length=4, verbose_name="GHG Target Effective To Year"
                    ),
                ),
                (
                    "ghg_target_gco2emj",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="GHG Target (gCO2e/MJ)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Greenhouse Gas Target",
                "db_table": "cas_fuel_eu_ghg_target",
            },
        ),
        migrations.CreateModel(
            name="FuelEUBunker",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "fuel_eu_bunker_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "bunker_type",
                    models.CharField(max_length=4, verbose_name="Bunker Type"),
                ),
                (
                    "ghg_intensity",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="GHG Intensity"
                    ),
                ),
                (
                    "lower_calorific_value",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=15,
                        verbose_name="Lower Calorific Value",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel Eu Bunker",
                "db_table": "cas_fuel_eu_bunker",
            },
        ),
        migrations.CreateModel(
            name="FuelEU",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("fuel_eu_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "base_year_week",
                    models.CharField(max_length=6, verbose_name="Base Year Week"),
                ),
                (
                    "fuel_energy_content",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=15,
                        verbose_name="Fuel Energy Content",
                    ),
                ),
                (
                    "ghg_penalty_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=15, verbose_name="GHG Penalty Rate"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "FUEL EU",
                "db_table": "cas_fuel_eu",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "exchange_rate_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "db_table": "cas_cost_exchange_rate",
            },
        ),
        migrations.CreateModel(
            name="ETSTSPort",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("ets_ts_port_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ets_ts_port_code",
                    models.CharField(max_length=10, verbose_name="ETS TS Port Code"),
                ),
                (
                    "ets_ts_port_name",
                    models.CharField(max_length=50, verbose_name="ETS TS Port Name"),
                ),
                (
                    "ets_ts_port_country_name",
                    models.CharField(
                        max_length=50, verbose_name="ETS TS Port Country Name"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETS TS Port",
                "db_table": "cas_ets_ts_port",
            },
        ),
        migrations.CreateModel(
            name="ETSEUA",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("ets_eua_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "eu_allowance",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="EU Allowance"
                    ),
                ),
                (
                    "euro_exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=15,
                        verbose_name="EURO Exchange Rate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETS EUA",
                "db_table": "cas_ets_eua",
            },
        ),
        migrations.CreateModel(
            name="ETSCountry",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("ets_country_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ets_country_code",
                    models.CharField(max_length=2, verbose_name="ETS Country Code"),
                ),
                (
                    "ets_country_name",
                    models.CharField(max_length=50, verbose_name="ETS Country Name"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETS Country",
                "db_table": "cas_ets_country",
            },
        ),
        migrations.CreateModel(
            name="ETSBunkerConsumption",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "ets_bunker_consumption_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "bunker_type",
                    models.CharField(
                        choices=[
                            ("LSFO", "Low Sulphur Fuel Oil"),
                            ("MGO", "Marine Gas Oil"),
                        ],
                        max_length=4,
                        verbose_name="Bunker Type",
                    ),
                ),
                (
                    "bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Bunker Consumption",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETS Bunker Consumption",
                "db_table": "cas_ets_bunker_consumption",
            },
        ),
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("distance_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "from_port_code",
                    models.CharField(max_length=10, verbose_name="From Port Code"),
                ),
                (
                    "to_port_code",
                    models.CharField(max_length=10, verbose_name="To Port Code"),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=10, max_digits=25, verbose_name="Distance"
                    ),
                ),
                (
                    "eca_distance",
                    models.DecimalField(
                        decimal_places=10, max_digits=25, verbose_name="ECA Distance"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distance",
                "db_table": "cas_cost_distance",
            },
        ),
        migrations.CreateModel(
            name="CharterCost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "charter_cost_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=4, verbose_name="Vessel Code"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("hire_from_date", models.DateTimeField(verbose_name="Hire From Date")),
                ("hire_to_date", models.DateTimeField(verbose_name="Hire To Date")),
                (
                    "hire_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Hire Rate"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charter Cost",
                "db_table": "cas_vessel_charter_cost",
            },
        ),
        migrations.CreateModel(
            name="CanalFee",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("canal_fee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "canal_fee",
                    models.DecimalField(
                        decimal_places=13, max_digits=25, verbose_name="Canal Fee"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal Fee",
                "db_table": "cas_cost_canal_fee",
            },
        ),
        migrations.CreateModel(
            name="BunkerPrice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "bunker_price_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "bunker_type",
                    models.CharField(
                        choices=[
                            ("LSFO", "Low Sulphur Fuel Oil"),
                            ("MGO", "Marine Gas Oil"),
                        ],
                        max_length=4,
                        verbose_name="Bunker Type",
                    ),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "bunker_price",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Bunker Price"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Price",
                "db_table": "cas_bunker_bunker_price",
            },
        ),
        migrations.CreateModel(
            name="BunkeringPort",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "bunkering_port_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "bunker_type",
                    models.CharField(
                        choices=[
                            ("LSFO", "Low Sulphur Fuel Oil"),
                            ("MGO", "Marine Gas Oil"),
                        ],
                        max_length=4,
                        verbose_name="Bunker Type",
                    ),
                ),
                (
                    "bunkering_port",
                    models.CharField(max_length=10, verbose_name="Bunkering Port"),
                ),
                (
                    "bunkering_port_ratio",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=15,
                        verbose_name="Bunkering Port Ratio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunkering Port",
                "db_table": "cas_bunker_bunkering_por",
            },
        ),
        migrations.CreateModel(
            name="BunkerConsumptionSea",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "bunker_consumption_sea_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "sea_speed",
                    models.DecimalField(
                        decimal_places=15, max_digits=20, verbose_name="Sea Speed"
                    ),
                ),
                (
                    "bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Bunker Consumption",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Consumption Sea",
                "db_table": "cas_bunker_consumption_sea",
            },
        ),
        migrations.CreateModel(
            name="BunkerConsumptionPort",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "bunker_consumption_port_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "port_stay_bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Port Stay Bunker Consumption",
                    ),
                ),
                (
                    "idling_bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Idling Bunker Consumption",
                    ),
                ),
                (
                    "pilot_inout_bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Pilot In/Out Bunker Consumption",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Consumption Port",
                "db_table": "cas_bunker_consumption_port",
            },
        ),
        migrations.CreateModel(
            name="LongRangeSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "long_range_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "start_port_berthing_year_week",
                    models.CharField(
                        max_length=6, verbose_name="Start Port Berthing Year Week"
                    ),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "schedule_change_status_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Ad hoc Call"),
                            ("I", "Phase In"),
                            ("L", "Vessel Slide"),
                            ("O", "Phase Out"),
                            ("S", "Port Omisson"),
                            ("R", "Port Call Swap"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Schedule Change Status Code",
                    ),
                ),
                (
                    "eta_initial_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ETA (Initial Arrival)"
                    ),
                ),
                (
                    "etb_initial_berthing",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ETB (Initial Berthing)"
                    ),
                ),
                (
                    "etd_initial_departure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ETD (Initial Departure)"
                    ),
                ),
                (
                    "terminal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Terminal Code",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Long Range Schedule",
                "db_table": "cas_schedule_long_range",
            },
        ),
        migrations.CreateModel(
            name="OwnVesselCost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "own_vessel_cost_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "slot_price",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Slot Price"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Own Vessel Cost",
                "db_table": "cas_cost_own_vessel_cost",
            },
        ),
        migrations.CreateModel(
            name="PortCharge",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("port_charge_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                (
                    "tonnage_port_yn",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        max_length=1,
                        verbose_name="Tonnage Port YN",
                    ),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "port_charge",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Port Charge"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port Charge",
                "db_table": "cas_cost_port_charge",
            },
        ),
        migrations.CreateModel(
            name="ProformaSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "proforma_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "vessel_service_lane_code",
                    models.CharField(
                        max_length=10, verbose_name="Vessel Service Lane Code"
                    ),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                (
                    "service_lane_standard",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Service Lane Standard"
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Duration"
                    ),
                ),
                (
                    "standard_service_speed",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Standard Service Speed",
                    ),
                ),
                (
                    "declared_capacity_class_code",
                    models.CharField(
                        max_length=5, verbose_name="Declared Capacity (Class Code)"
                    ),
                ),
                ("declared_count", models.IntegerField(verbose_name="Declared Count")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "etb_day_code",
                    models.CharField(max_length=3, verbose_name="ETB Day Code"),
                ),
                (
                    "etb_day_time",
                    models.CharField(max_length=4, verbose_name="ETB Day Time"),
                ),
                ("etb_day_number", models.IntegerField(verbose_name="ETB Day Number")),
                (
                    "etd_day_code",
                    models.CharField(max_length=3, verbose_name="ETD Day Code"),
                ),
                (
                    "etd_day_time",
                    models.CharField(max_length=4, verbose_name="ETD Day Time"),
                ),
                ("etd_day_number", models.IntegerField(verbose_name="ETD Day Number")),
                ("link_distance", models.IntegerField(verbose_name="Link Distance")),
                (
                    "link_speed",
                    models.DecimalField(
                        decimal_places=3, max_digits=7, verbose_name="Link Speed"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proforma Schedule",
                "verbose_name_plural": "Proforma Schedules",
                "db_table": "cas_schedule_proforma",
            },
        ),
        migrations.CreateModel(
            name="TSCost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("ts_cost_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "full_empty_code",
                    models.CharField(
                        choices=[("F", "Full"), ("E", "Empty")],
                        max_length=1,
                        verbose_name="Full Empty Code",
                    ),
                ),
                (
                    "container_code",
                    models.CharField(
                        choices=[
                            ("D2", "D2"),
                            ("D4", "D4"),
                            ("D5", "D5"),
                            ("D7", "D7"),
                            ("R2", "R2"),
                            ("R5", "R5"),
                        ],
                        max_length=4,
                        verbose_name="Container Code",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("ts_cost", models.IntegerField(verbose_name="TS Cost")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "TS Cost",
                "db_table": "cas_cost_ts_cost",
            },
        ),
        migrations.CreateModel(
            name="VesselCapacity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "vessel_capacity_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "effective_from_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Effective From Date"
                    ),
                ),
                ("teu_capacity", models.IntegerField(verbose_name="TEU Capacity")),
                (
                    "reefer_capacity",
                    models.IntegerField(verbose_name="Reefer Capacity"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Capacity",
                "db_table": "cas_vessel_capacity",
            },
        ),
        migrations.CreateModel(
            name="VesselInfo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("vessel_info_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vessel_code",
                    models.CharField(max_length=4, verbose_name="Vessel Code"),
                ),
                (
                    "vessel_name",
                    models.CharField(max_length=50, verbose_name="Vessel Name"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "own_yn",
                    models.CharField(
                        choices=[("O", "Own"), ("C", "Chartered")],
                        max_length=1,
                        verbose_name="Own YN",
                    ),
                ),
                (
                    "contract_actual_delivery_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Contract Actual Delivery Date",
                    ),
                ),
                (
                    "delivery_max_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Max Date"
                    ),
                ),
                (
                    "contract_actual_redelivery_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Contract Actual Redelivery Date",
                    ),
                ),
                (
                    "redelivery_max_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Redelivery Max Date"
                    ),
                ),
                (
                    "next_dock_due",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock Due"
                    ),
                ),
                (
                    "next_dock_in_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock In Date"
                    ),
                ),
                (
                    "next_dock_out_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock Out Date"
                    ),
                ),
                (
                    "next_dock_shipyard",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Next Dock Shipyard",
                    ),
                ),
                (
                    "built_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Built Date"
                    ),
                ),
                (
                    "built_shipyard",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Built Shipyard",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="DATA_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Info",
                "db_table": "cas_vessel_info",
            },
        ),
    ]
