# Generated by Django 5.2.10 on 2026-02-07 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InputDataSnapshot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "data_id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Data ID (Snapshot Key)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Base Year Month",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Input Data Snapshot",
                "verbose_name_plural": "Input Data Snapshot",
                "db_table": "cas_input_data_snapshot",
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "exchange_rate_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "db_table": "cas_cost_exchange_rate",
                "unique_together": {("base_year_month", "currency_code")},
            },
        ),
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("distance_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "from_port_code",
                    models.CharField(max_length=10, verbose_name="From Port Code"),
                ),
                (
                    "to_port_code",
                    models.CharField(max_length=10, verbose_name="To Port Code"),
                ),
                ("distance", models.IntegerField(verbose_name="Distance")),
                ("eca_distance", models.IntegerField(verbose_name="ECA Distance")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distance",
                "db_table": "cas_cost_distance",
                "unique_together": {("from_port_code", "to_port_code")},
            },
        ),
        migrations.CreateModel(
            name="CharterCost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "charter_cost_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=4, verbose_name="Vessel Code"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("hire_from_date", models.DateTimeField(verbose_name="Hire From Date")),
                ("hire_to_date", models.DateTimeField(verbose_name="Hire To Date")),
                ("hire_rate", models.IntegerField(verbose_name="Hire Rate")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charter Cost",
                "db_table": "cas_vessel_charter_cost",
                "unique_together": {("vessel_code", "currency_code", "hire_from_date")},
            },
        ),
        migrations.CreateModel(
            name="CanalFee",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("canal_fee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "canal_fee",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Canal Fee"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal Fee",
                "db_table": "cas_cost_canal_fee",
                "unique_together": {("vessel_code", "direction", "port_code")},
            },
        ),
        migrations.CreateModel(
            name="BunkerPrice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "bunker_price_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "bunker_type",
                    models.CharField(
                        choices=[
                            ("LSFO", "Low Sulphur Fuel Oil"),
                            ("MGO", "Marine Gas Oil"),
                        ],
                        max_length=4,
                        verbose_name="Bunker Type",
                    ),
                ),
                (
                    "bunker_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Bunker Price"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Price",
                "db_table": "cas_bunker_bunker_price",
                "unique_together": {
                    ("base_year_month", "trade_code", "lane_code", "bunker_type")
                },
            },
        ),
        migrations.CreateModel(
            name="BunkerConsumptionSea",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "bunker_consumption_sea_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "sea_speed",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Sea Speed"
                    ),
                ),
                (
                    "bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Bunker Consumption",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Consumption Sea",
                "db_table": "cas_bunker_consumption_sea",
                "unique_together": {
                    ("base_year_month", "nominal_capacity", "sea_speed")
                },
            },
        ),
        migrations.CreateModel(
            name="BunkerConsumptionPort",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "bunker_consumption_port_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "port_stay_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Port Stay Bunker Consumption",
                    ),
                ),
                (
                    "idling_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Idling Bunker Consumption",
                    ),
                ),
                (
                    "pilot_inout_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Pilot In/Out Bunker Consumption",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Consumption Port",
                "db_table": "cas_bunker_consumption_port",
                "unique_together": {("base_year_month", "nominal_capacity")},
            },
        ),
        migrations.CreateModel(
            name="LongRangeSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "long_range_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "start_port_berthing_year_week",
                    models.CharField(
                        max_length=6, verbose_name="Start Port Berthing Year Week"
                    ),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "schedule_change_status_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Ad hoc Call"),
                            ("I", "Phase In"),
                            ("L", "Vessel Slide"),
                            ("O", "Phase Out"),
                            ("S", "Port Omisson"),
                            ("R", "Port Call Swap"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Schedule Change Status Code",
                    ),
                ),
                (
                    "eta_initial_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ETA (Initial Arrival)"
                    ),
                ),
                (
                    "etb_initial_berthing",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ETB (Initial Berthing)"
                    ),
                ),
                (
                    "etd_initial_departure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ETD (Initial Departure)"
                    ),
                ),
                (
                    "terminal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Terminal Code",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Long Range Schedule",
                "db_table": "cas_schedule_long_range",
                "unique_together": {
                    (
                        "lane_code",
                        "vessel_code",
                        "voyage_number",
                        "direction",
                        "port_code",
                        "calling_port_indicator_seq",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="master_week_period",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "master_week_period_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("base_year", models.IntegerField(verbose_name="Base Year")),
                ("base_week", models.IntegerField(verbose_name="Base Week")),
                ("base_month", models.IntegerField(verbose_name="Base Month")),
                ("week_start_date", models.DateTimeField(verbose_name="Week Start")),
                ("week_end_date", models.DateTimeField(verbose_name="Week End")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Week Period",
                "db_table": "cas_week_period",
                "unique_together": {("base_week",)},
            },
        ),
        migrations.CreateModel(
            name="ProformaSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "proforma_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                (
                    "lane_standard",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Lane Standard"
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Duration"
                    ),
                ),
                (
                    "declared_capacity",
                    models.CharField(
                        max_length=5, verbose_name="Declared Capacity (Class Code)"
                    ),
                ),
                ("declared_count", models.IntegerField(verbose_name="Declared Count")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "turn_port_pair_code",
                    models.CharField(
                        choices=[("Y", "Y"), ("N", "N")],
                        max_length=3,
                        verbose_name="ETB Day Code",
                    ),
                ),
                (
                    "pilot_in_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=3,
                        max_digits=5,
                        verbose_name="Pilot In Hours",
                    ),
                ),
                (
                    "etb_day_code",
                    models.CharField(max_length=3, verbose_name="ETB Day Code"),
                ),
                (
                    "etb_day_time",
                    models.CharField(max_length=4, verbose_name="ETB Day Time"),
                ),
                ("etb_day_number", models.IntegerField(verbose_name="ETB Day Number")),
                (
                    "actual_work_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=30,
                        max_digits=5,
                        verbose_name="Actual Work Hours(ETD - ETB)",
                    ),
                ),
                (
                    "etd_day_code",
                    models.CharField(max_length=3, verbose_name="ETD Day Code"),
                ),
                (
                    "etd_day_time",
                    models.CharField(max_length=4, verbose_name="ETD Day Time"),
                ),
                ("etd_day_number", models.IntegerField(verbose_name="ETD Day Number")),
                (
                    "pilot_out_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=3,
                        max_digits=5,
                        verbose_name="Pilot Out Hours",
                    ),
                ),
                (
                    "link_distance",
                    models.IntegerField(default=0, verbose_name="Link Distance"),
                ),
                (
                    "link_eca_distance",
                    models.IntegerField(
                        default=0, null=True, verbose_name="Link ECA Distance"
                    ),
                ),
                (
                    "link_speed",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="Link Speed",
                    ),
                ),
                (
                    "sea_hours",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="Sea Hours",
                    ),
                ),
                (
                    "terminal_code",
                    models.CharField(max_length=10, verbose_name="Terminal Code"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proforma Schedule",
                "db_table": "cas_schedule_proforma",
                "unique_together": {
                    (
                        "lane_code",
                        "proforma_name",
                        "direction",
                        "port_code",
                        "calling_port_indicator_seq",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="TSCost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("ts_cost_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "full_empty_code",
                    models.CharField(
                        choices=[("F", "Full"), ("E", "Empty")],
                        max_length=1,
                        verbose_name="Full Empty Code",
                    ),
                ),
                (
                    "container_code",
                    models.CharField(
                        choices=[
                            ("D2", "D2"),
                            ("D4", "D4"),
                            ("D5", "D5"),
                            ("D7", "D7"),
                            ("R2", "R2"),
                            ("R5", "R5"),
                        ],
                        max_length=4,
                        verbose_name="Container Code",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("ts_cost", models.IntegerField(verbose_name="TS Cost")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "TS Cost",
                "db_table": "cas_cost_ts_cost",
                "unique_together": {
                    (
                        "base_year_month",
                        "port_code",
                        "full_empty_code",
                        "container_code",
                        "currency_code",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="VesselCapacity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "vessel_capacity_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "effective_from_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Effective From Date"
                    ),
                ),
                ("teu_capacity", models.IntegerField(verbose_name="TEU Capacity")),
                (
                    "reefer_capacity",
                    models.IntegerField(verbose_name="Reefer Capacity"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Capacity",
                "db_table": "cas_vessel_capacity",
                "unique_together": {
                    (
                        "trade_code",
                        "lane_code",
                        "vessel_code",
                        "voyage_number",
                        "direction",
                        "effective_from_date",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="VesselInfo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("vessel_info_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vessel_code",
                    models.CharField(max_length=4, verbose_name="Vessel Code"),
                ),
                (
                    "vessel_name",
                    models.CharField(max_length=50, verbose_name="Vessel Name"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "own_yn",
                    models.CharField(
                        choices=[("O", "Own"), ("C", "Chartered")],
                        max_length=1,
                        verbose_name="Own YN",
                    ),
                ),
                (
                    "delivery_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Delivery Port Code",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Date"
                    ),
                ),
                (
                    "redelivery_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Redelivery Port Code",
                    ),
                ),
                (
                    "redelivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Redelivery Date"
                    ),
                ),
                (
                    "next_dock_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Next Dock Port Code",
                    ),
                ),
                (
                    "next_dock_in_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock In Date"
                    ),
                ),
                (
                    "next_dock_out_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock Out Date"
                    ),
                ),
                (
                    "built_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Built Port Code",
                    ),
                ),
                (
                    "built_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Built Date"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "data_id",
                    models.ForeignKey(
                        db_column="data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.inputdatasnapshot",
                        verbose_name="Data ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Info",
                "db_table": "cas_vessel_info",
                "unique_together": {("vessel_code",)},
            },
        ),
    ]
