# Generated by Django 5.2.10 on 2026-02-09 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseBunkerConsumptionPort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "port_stay_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Port Stay Consumption",
                    ),
                ),
                (
                    "idling_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Idling Consumption",
                    ),
                ),
                (
                    "pilot_inout_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Pilot In/Out Consumption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Bunker Consumption Port",
                "db_table": "base_bunker_consumption_port",
                "unique_together": {("base_year_month", "nominal_capacity")},
            },
        ),
        migrations.CreateModel(
            name="BaseBunkerConsumptionSea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "sea_speed",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Sea Speed"
                    ),
                ),
                (
                    "bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Bunker Consumption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Bunker Consumption Sea",
                "db_table": "base_bunker_consumption_sea",
                "unique_together": {
                    ("base_year_month", "nominal_capacity", "sea_speed")
                },
            },
        ),
        migrations.CreateModel(
            name="BaseBunkerPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "bunker_type",
                    models.CharField(
                        choices=[
                            ("LSFO", "Low Sulphur Fuel Oil"),
                            ("MGO", "Marine Gas Oil"),
                        ],
                        max_length=4,
                        verbose_name="Bunker Type",
                    ),
                ),
                (
                    "bunker_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Bunker Price"
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Bunker Price",
                "db_table": "base_bunker_price",
                "unique_together": {
                    ("base_year_month", "trade_code", "lane_code", "bunker_type")
                },
            },
        ),
        migrations.CreateModel(
            name="BaseCanalFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "canal_fee",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Canal Fee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Canal Fee",
                "db_table": "base_cost_canal_fee",
                "unique_together": {("vessel_code", "direction", "port_code")},
            },
        ),
        migrations.CreateModel(
            name="BaseCharterCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=4, verbose_name="Vessel Code"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("hire_from_date", models.DateTimeField(verbose_name="Hire From Date")),
                ("hire_to_date", models.DateTimeField(verbose_name="Hire To Date")),
                ("hire_rate", models.IntegerField(verbose_name="Hire Rate")),
            ],
            options={
                "verbose_name": "Standard Charter Cost",
                "db_table": "base_vessel_charter_cost",
                "unique_together": {("vessel_code", "currency_code", "hire_from_date")},
            },
        ),
        migrations.CreateModel(
            name="BaseDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_port_code",
                    models.CharField(max_length=10, verbose_name="From Port Code"),
                ),
                (
                    "to_port_code",
                    models.CharField(max_length=10, verbose_name="To Port Code"),
                ),
                ("distance", models.IntegerField(verbose_name="Distance")),
                ("eca_distance", models.IntegerField(verbose_name="ECA Distance")),
            ],
            options={
                "verbose_name": "Standard Distance",
                "db_table": "base_cost_distance",
                "unique_together": {("from_port_code", "to_port_code")},
            },
        ),
        migrations.CreateModel(
            name="BaseFixedVesselDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=20, verbose_name="Vessel Code"),
                ),
                (
                    "deployment_type",
                    models.CharField(
                        choices=[
                            ("I", "Must Go (Include)"),
                            ("E", "Not Allowed (Exclude)"),
                            ("P", "Preferred"),
                            ("S", "Substitute"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="Deployment Type",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Remark"
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Fixed Deployment",
                "db_table": "base_constraint_fixed_deployment",
                "unique_together": {("lane_code", "vessel_code")},
            },
        ),
        migrations.CreateModel(
            name="BaseFixedVesselEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=20, verbose_name="Vessel Code"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PI", "Phase In"),
                            ("PO", "Phase Out"),
                            ("DD", "Dry Dock"),
                            ("OH", "On-Hire"),
                            ("OF", "Off-Hire"),
                            ("LU", "Lay-Up"),
                            ("RA", "Re-Activate"),
                        ],
                        max_length=2,
                        verbose_name="Event Type",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event Date")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Fixed Event",
                "db_table": "base_constraint_fixed_event",
                "unique_together": {
                    ("vessel_code", "port_code", "event_type", "event_date")
                },
            },
        ),
        migrations.CreateModel(
            name="BaseLongRangeSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "start_port_berthing_year_week",
                    models.CharField(
                        max_length=6, verbose_name="Start Port Berthing Year Week"
                    ),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "schedule_change_status_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Ad hoc Call"),
                            ("I", "Phase In"),
                            ("L", "Vessel Slide"),
                            ("O", "Phase Out"),
                            ("S", "Port Omisson"),
                            ("R", "Port Call Swap"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Change Status",
                    ),
                ),
                (
                    "eta_initial_arrival",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETA"),
                ),
                (
                    "etb_initial_berthing",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETB"),
                ),
                (
                    "etd_initial_departure",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETD"),
                ),
                (
                    "terminal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Terminal Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Long Range Schedule",
                "db_table": "base_schedule_long_range",
                "unique_together": {
                    (
                        "lane_code",
                        "vessel_code",
                        "voyage_number",
                        "direction",
                        "port_code",
                        "calling_port_indicator_seq",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="BasePortConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "terminal_code",
                    models.CharField(
                        default="All", max_length=10, verbose_name="Terminal Code"
                    ),
                ),
                (
                    "exclude_vessel_class",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Excluded Vessel Class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Port Constraint",
                "db_table": "base_constraint_port",
                "unique_together": {("port_code", "terminal_code")},
            },
        ),
        migrations.CreateModel(
            name="BaseProformaSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                ("effective_date", models.DateTimeField(verbose_name="Effective Date")),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Duration"
                    ),
                ),
                (
                    "declared_capacity",
                    models.CharField(max_length=5, verbose_name="Declared Capacity"),
                ),
                ("declared_count", models.IntegerField(verbose_name="Declared Count")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "turn_port_info_code",
                    models.CharField(
                        choices=[("Y", "Y"), ("N", "N")],
                        max_length=3,
                        verbose_name="Turn Port Info",
                    ),
                ),
                (
                    "pilot_in_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=3,
                        max_digits=5,
                        verbose_name="Pilot In Hours",
                    ),
                ),
                (
                    "etb_day_code",
                    models.CharField(max_length=3, verbose_name="ETB Day Code"),
                ),
                (
                    "etb_day_time",
                    models.CharField(max_length=4, verbose_name="ETB Day Time"),
                ),
                ("etb_day_number", models.IntegerField(verbose_name="ETB Day Number")),
                (
                    "actual_work_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=30,
                        max_digits=5,
                        verbose_name="Actual Work Hours",
                    ),
                ),
                (
                    "etd_day_code",
                    models.CharField(max_length=3, verbose_name="ETD Day Code"),
                ),
                (
                    "etd_day_time",
                    models.CharField(max_length=4, verbose_name="ETD Day Time"),
                ),
                ("etd_day_number", models.IntegerField(verbose_name="ETD Day Number")),
                (
                    "pilot_out_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=3,
                        max_digits=5,
                        verbose_name="Pilot Out Hours",
                    ),
                ),
                (
                    "link_distance",
                    models.IntegerField(default=0, verbose_name="Link Distance"),
                ),
                (
                    "link_eca_distance",
                    models.IntegerField(
                        default=0, null=True, verbose_name="Link ECA Distance"
                    ),
                ),
                (
                    "link_speed",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="Link Speed",
                    ),
                ),
                (
                    "sea_hours",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="Sea Hours",
                    ),
                ),
                (
                    "terminal_code",
                    models.CharField(max_length=10, verbose_name="Terminal Code"),
                ),
            ],
            options={
                "verbose_name": "Standard Proforma Schedule",
                "db_table": "base_schedule_proforma",
                "unique_together": {
                    (
                        "lane_code",
                        "proforma_name",
                        "direction",
                        "port_code",
                        "calling_port_indicator_seq",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="BaseTSCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("ts_cost", models.IntegerField(verbose_name="TS Cost")),
            ],
            options={
                "verbose_name": "Standard TS Cost",
                "db_table": "base_cost_ts_cost",
                "unique_together": {("base_year_month", "port_code", "currency_code")},
            },
        ),
        migrations.CreateModel(
            name="BaseVesselCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                ("teu_capacity", models.IntegerField(verbose_name="TEU Capacity")),
                (
                    "reefer_capacity",
                    models.IntegerField(verbose_name="Reefer Capacity"),
                ),
            ],
            options={
                "verbose_name": "Standard Vessel Capacity",
                "db_table": "base_vessel_capacity",
                "unique_together": {
                    (
                        "trade_code",
                        "lane_code",
                        "vessel_code",
                        "voyage_number",
                        "direction",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="BaseVesselInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "vessel_name",
                    models.CharField(max_length=50, verbose_name="Vessel Name"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "own_yn",
                    models.CharField(
                        choices=[("O", "Own"), ("C", "Chartered")],
                        max_length=1,
                        verbose_name="Own YN",
                    ),
                ),
                (
                    "delivery_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Delivery Port Code",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Date"
                    ),
                ),
                (
                    "redelivery_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Redelivery Port Code",
                    ),
                ),
                (
                    "redelivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Redelivery Date"
                    ),
                ),
                (
                    "next_dock_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Next Dock Port Code",
                    ),
                ),
                (
                    "next_dock_in_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock In Date"
                    ),
                ),
                (
                    "next_dock_out_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock Out Date"
                    ),
                ),
                (
                    "built_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Built Port Code",
                    ),
                ),
                (
                    "built_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Built Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Vessel Info",
                "db_table": "base_vessel_info",
                "unique_together": {("vessel_code",)},
            },
        ),
        migrations.CreateModel(
            name="ScenarioInfo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "id",
                    models.CharField(
                        db_column="scenario_id",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Scenario ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "base_year_month",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Base Year Month",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("T", "TEST"), ("N", "Not used")],
                        default="T",
                        max_length=50,
                        verbose_name="Scenario Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario Info",
                "db_table": "sce_scenario_info",
            },
        ),
        migrations.CreateModel(
            name="BaseWeekPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("base_year", models.IntegerField(verbose_name="Base Year")),
                ("base_week", models.IntegerField(verbose_name="Base Week")),
                ("base_month", models.IntegerField(verbose_name="Base Month")),
                ("week_start_date", models.DateTimeField(verbose_name="Week Start")),
                ("week_end_date", models.DateTimeField(verbose_name="Week End")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Week Period",
                "db_table": "base_week_period",
                "unique_together": {("base_year", "base_week")},
            },
        ),
        migrations.CreateModel(
            name="ProformaSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                ("effective_date", models.DateTimeField(verbose_name="Effective Date")),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Duration"
                    ),
                ),
                (
                    "declared_capacity",
                    models.CharField(max_length=5, verbose_name="Declared Capacity"),
                ),
                ("declared_count", models.IntegerField(verbose_name="Declared Count")),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "turn_port_info_code",
                    models.CharField(
                        choices=[("Y", "Y"), ("N", "N")],
                        max_length=3,
                        verbose_name="Turn Port Info",
                    ),
                ),
                (
                    "pilot_in_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=3,
                        max_digits=5,
                        verbose_name="Pilot In Hours",
                    ),
                ),
                (
                    "etb_day_code",
                    models.CharField(max_length=3, verbose_name="ETB Day Code"),
                ),
                (
                    "etb_day_time",
                    models.CharField(max_length=4, verbose_name="ETB Day Time"),
                ),
                ("etb_day_number", models.IntegerField(verbose_name="ETB Day Number")),
                (
                    "actual_work_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=30,
                        max_digits=5,
                        verbose_name="Actual Work Hours",
                    ),
                ),
                (
                    "etd_day_code",
                    models.CharField(max_length=3, verbose_name="ETD Day Code"),
                ),
                (
                    "etd_day_time",
                    models.CharField(max_length=4, verbose_name="ETD Day Time"),
                ),
                ("etd_day_number", models.IntegerField(verbose_name="ETD Day Number")),
                (
                    "pilot_out_hours",
                    models.DecimalField(
                        decimal_places=3,
                        default=3,
                        max_digits=5,
                        verbose_name="Pilot Out Hours",
                    ),
                ),
                (
                    "link_distance",
                    models.IntegerField(default=0, verbose_name="Link Distance"),
                ),
                (
                    "link_eca_distance",
                    models.IntegerField(
                        default=0, null=True, verbose_name="Link ECA Distance"
                    ),
                ),
                (
                    "link_speed",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="Link Speed",
                    ),
                ),
                (
                    "sea_hours",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="Sea Hours",
                    ),
                ),
                (
                    "terminal_code",
                    models.CharField(max_length=10, verbose_name="Terminal Code"),
                ),
                (
                    "proforma_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proforma Schedule",
                "db_table": "sce_schedule_proforma",
                "unique_together": {
                    (
                        "scenario",
                        "lane_code",
                        "proforma_name",
                        "direction",
                        "port_code",
                        "calling_port_indicator_seq",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="PortConstraint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "terminal_code",
                    models.CharField(
                        default="All", max_length=10, verbose_name="Terminal Code"
                    ),
                ),
                (
                    "exclude_vessel_class",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Excluded Vessel Class",
                    ),
                ),
                ("constraint_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port Constraint",
                "db_table": "sce_constraint_port",
                "unique_together": {("scenario", "port_code", "terminal_code")},
            },
        ),
        migrations.CreateModel(
            name="LongRangeSchedule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "start_port_berthing_year_week",
                    models.CharField(
                        max_length=6, verbose_name="Start Port Berthing Year Week"
                    ),
                ),
                (
                    "proforma_name",
                    models.CharField(max_length=30, verbose_name="Proforma Name"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "calling_port_indicator_seq",
                    models.CharField(
                        max_length=2, verbose_name="Calling Port Indicator Seq."
                    ),
                ),
                (
                    "calling_port_seq",
                    models.IntegerField(verbose_name="Calling Port Seq."),
                ),
                (
                    "schedule_change_status_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Ad hoc Call"),
                            ("I", "Phase In"),
                            ("L", "Vessel Slide"),
                            ("O", "Phase Out"),
                            ("S", "Port Omisson"),
                            ("R", "Port Call Swap"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Change Status",
                    ),
                ),
                (
                    "eta_initial_arrival",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETA"),
                ),
                (
                    "etb_initial_berthing",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETB"),
                ),
                (
                    "etd_initial_departure",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETD"),
                ),
                (
                    "terminal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Terminal Code",
                    ),
                ),
                (
                    "long_range_schedule_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Long Range Schedule",
                "db_table": "sce_schedule_long_range",
                "unique_together": {
                    (
                        "scenario",
                        "lane_code",
                        "vessel_code",
                        "voyage_number",
                        "direction",
                        "port_code",
                        "calling_port_indicator_seq",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="FixedVesselEvent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=20, verbose_name="Vessel Code"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PI", "Phase In"),
                            ("PO", "Phase Out"),
                            ("DD", "Dry Dock"),
                            ("OH", "On-Hire"),
                            ("OF", "Off-Hire"),
                            ("LU", "Lay-Up"),
                            ("RA", "Re-Activate"),
                        ],
                        max_length=2,
                        verbose_name="Event Type",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Event Date")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("fixed_event_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Vessel Event",
                "db_table": "sce_constraint_fixed_event",
                "unique_together": {
                    ("scenario", "vessel_code", "port_code", "event_type", "event_date")
                },
            },
        ),
        migrations.CreateModel(
            name="FixedVesselDeployment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=20, verbose_name="Vessel Code"),
                ),
                (
                    "deployment_type",
                    models.CharField(
                        choices=[
                            ("I", "Must Go (Include)"),
                            ("E", "Not Allowed (Exclude)"),
                            ("P", "Preferred"),
                            ("S", "Substitute"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="Deployment Type",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Remark"
                    ),
                ),
                (
                    "fixed_deployment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Vessel Deployment",
                "db_table": "sce_constraint_fixed_deployment",
                "unique_together": {("scenario", "lane_code", "vessel_code")},
            },
        ),
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "from_port_code",
                    models.CharField(max_length=10, verbose_name="From Port Code"),
                ),
                (
                    "to_port_code",
                    models.CharField(max_length=10, verbose_name="To Port Code"),
                ),
                ("distance", models.IntegerField(verbose_name="Distance")),
                ("eca_distance", models.IntegerField(verbose_name="ECA Distance")),
                ("distance_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distance",
                "db_table": "sce_cost_distance",
                "unique_together": {("scenario", "from_port_code", "to_port_code")},
            },
        ),
        migrations.CreateModel(
            name="CharterCost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=4, verbose_name="Vessel Code"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("hire_from_date", models.DateTimeField(verbose_name="Hire From Date")),
                ("hire_to_date", models.DateTimeField(verbose_name="Hire To Date")),
                ("hire_rate", models.IntegerField(verbose_name="Hire Rate")),
                (
                    "charter_cost_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charter Cost",
                "db_table": "sce_vessel_charter_cost",
                "unique_together": {
                    ("scenario", "vessel_code", "currency_code", "hire_from_date")
                },
            },
        ),
        migrations.CreateModel(
            name="CanalFee",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "canal_fee",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Canal Fee"
                    ),
                ),
                ("canal_fee_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal Fee",
                "db_table": "sce_cost_canal_fee",
                "unique_together": {
                    ("scenario", "vessel_code", "direction", "port_code")
                },
            },
        ),
        migrations.CreateModel(
            name="BunkerPrice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "bunker_type",
                    models.CharField(
                        choices=[
                            ("LSFO", "Low Sulphur Fuel Oil"),
                            ("MGO", "Marine Gas Oil"),
                        ],
                        max_length=4,
                        verbose_name="Bunker Type",
                    ),
                ),
                (
                    "bunker_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="Bunker Price"
                    ),
                ),
                (
                    "bunker_price_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Price",
                "db_table": "sce_bunker_price",
                "unique_together": {
                    (
                        "scenario",
                        "base_year_month",
                        "trade_code",
                        "lane_code",
                        "bunker_type",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="BunkerConsumptionSea",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "sea_speed",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Sea Speed"
                    ),
                ),
                (
                    "bunker_consumption",
                    models.DecimalField(
                        decimal_places=13,
                        max_digits=25,
                        verbose_name="Bunker Consumption",
                    ),
                ),
                (
                    "bunker_consumption_sea_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Consumption Sea",
                "db_table": "sce_bunker_consumption_sea",
                "unique_together": {
                    ("scenario", "base_year_month", "nominal_capacity", "sea_speed")
                },
            },
        ),
        migrations.CreateModel(
            name="BunkerConsumptionPort",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "port_stay_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Port Stay Consumption",
                    ),
                ),
                (
                    "idling_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Idling Consumption",
                    ),
                ),
                (
                    "pilot_inout_bunker_consumption",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Pilot In/Out Consumption",
                    ),
                ),
                (
                    "bunker_consumption_port_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bunker Consumption Port",
                "db_table": "sce_bunker_consumption_port",
                "unique_together": {
                    ("scenario", "base_year_month", "nominal_capacity")
                },
            },
        ),
        migrations.CreateModel(
            name="TSCost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "base_year_month",
                    models.CharField(max_length=6, verbose_name="Base Year Month"),
                ),
                (
                    "port_code",
                    models.CharField(max_length=10, verbose_name="Port Code"),
                ),
                (
                    "currency_code",
                    models.CharField(max_length=3, verbose_name="Currency Code"),
                ),
                ("ts_cost", models.IntegerField(verbose_name="TS Cost")),
                ("ts_cost_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "TS Cost",
                "db_table": "sce_cost_ts_cost",
                "unique_together": {
                    ("scenario", "base_year_month", "port_code", "currency_code")
                },
            },
        ),
        migrations.CreateModel(
            name="VesselCapacity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "trade_code",
                    models.CharField(max_length=10, verbose_name="Trade Code"),
                ),
                (
                    "lane_code",
                    models.CharField(max_length=10, verbose_name="Lane Code"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "voyage_number",
                    models.CharField(max_length=20, verbose_name="Voyage Number"),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("E", "East"),
                            ("W", "West"),
                            ("S", "South"),
                            ("N", "North"),
                        ],
                        max_length=2,
                        verbose_name="Direction",
                    ),
                ),
                ("teu_capacity", models.IntegerField(verbose_name="TEU Capacity")),
                (
                    "reefer_capacity",
                    models.IntegerField(verbose_name="Reefer Capacity"),
                ),
                (
                    "vessel_capacity_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Capacity",
                "db_table": "sce_vessel_capacity",
                "unique_together": {
                    (
                        "scenario",
                        "trade_code",
                        "lane_code",
                        "vessel_code",
                        "voyage_number",
                        "direction",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="VesselInfo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "vessel_code",
                    models.CharField(max_length=10, verbose_name="Vessel Code"),
                ),
                (
                    "vessel_name",
                    models.CharField(max_length=50, verbose_name="Vessel Name"),
                ),
                (
                    "nominal_capacity",
                    models.IntegerField(verbose_name="Nominal Capacity"),
                ),
                (
                    "own_yn",
                    models.CharField(
                        choices=[("O", "Own"), ("C", "Chartered")],
                        max_length=1,
                        verbose_name="Own YN",
                    ),
                ),
                (
                    "delivery_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Delivery Port Code",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivery Date"
                    ),
                ),
                (
                    "redelivery_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Redelivery Port Code",
                    ),
                ),
                (
                    "redelivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Redelivery Date"
                    ),
                ),
                (
                    "next_dock_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Next Dock Port Code",
                    ),
                ),
                (
                    "next_dock_in_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock In Date"
                    ),
                ),
                (
                    "next_dock_out_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Next Dock Out Date"
                    ),
                ),
                (
                    "built_port_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Built Port Code",
                    ),
                ),
                (
                    "built_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Built Date"
                    ),
                ),
                ("vessel_info_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="input_data.scenarioinfo",
                        verbose_name="Scenario ID",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vessel Info",
                "db_table": "sce_vessel_info",
                "unique_together": {("scenario", "vessel_code")},
            },
        ),
    ]
