# Generated by Django 5.2.10 on 2026-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseweekperiod",
            name="base_month",
            field=models.CharField(max_length=2, verbose_name="Base Month / MM"),
        ),
        migrations.AlterField(
            model_name="baseweekperiod",
            name="base_week",
            field=models.CharField(max_length=2, verbose_name="Base Week / WK"),
        ),
        migrations.AlterField(
            model_name="baseweekperiod",
            name="base_year",
            field=models.CharField(max_length=4, verbose_name="Base Year / YYYY"),
        ),
    ]
