# Generated by Django 5.2.10 on 2026-03-08 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaneProformaMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this proforma is currently applied to the lane",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        db_column="lane_code",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="input_data.masterlane",
                        verbose_name="Lane Code",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        db_column="proforma_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lane_mappings",
                        to="input_data.proformaschedule",
                        verbose_name="Applied Proforma",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        db_column="scenario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lane_proforma_mappings",
                        to="input_data.scenarioinfo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lane Proforma Mapping",
                "verbose_name_plural": "Lane Proforma Mappings",
                "db_table": "sce_lane_proforma_mapping",
                "ordering": ["scenario", "lane"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario", "lane"), name="uq_laneproformamapping"
                    )
                ],
            },
        ),
    ]
