# Generated by Django 5.2.10 on 2026-03-11 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bunkerconsumptionport",
            index=models.Index(
                fields=["scenario", "base_year_month"],
                name="idx_sce_bcp_scenario_month",
            ),
        ),
        migrations.AddIndex(
            model_name="bunkerconsumptionport",
            index=models.Index(
                fields=["scenario", "base_year_month", "vessel_capacity"],
                name="idx_sce_bcp_composite",
            ),
        ),
        migrations.AddIndex(
            model_name="bunkerconsumptionsea",
            index=models.Index(
                fields=["scenario", "base_year_month"],
                name="idx_sce_bcs_scenario_month",
            ),
        ),
        migrations.AddIndex(
            model_name="bunkerconsumptionsea",
            index=models.Index(
                fields=["scenario", "base_year_month", "vessel_capacity", "sea_speed"],
                name="idx_sce_bcs_composite",
            ),
        ),
    ]
