# Generated by Django 5.2.10 on 2026-02-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proformaschedule",
            name="link_eca_distance",
            field=models.IntegerField(default=0, verbose_name="Link ECA Distance"),
        ),
        migrations.AlterField(
            model_name="proformaschedule",
            name="actual_work_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=30,
                max_digits=5,
                verbose_name="Actual Work Hours(ETD - ETB)",
            ),
        ),
        migrations.AlterField(
            model_name="proformaschedule",
            name="link_distance",
            field=models.IntegerField(default=0, verbose_name="Link Distance"),
        ),
    ]
