# Generated by Django 5.2.10 on 2026-03-09 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("input_data", "0002_add_lane_proforma_mapping"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="laneproformamapping",
            name="uq_laneproformamapping",
        ),
        migrations.AddConstraint(
            model_name="laneproformamapping",
            constraint=models.UniqueConstraint(
                fields=("scenario", "lane", "proforma"), name="uq_laneproformamapping"
            ),
        ),
    ]
