repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Ruff (린팅 + 정렬) - isort, flake8 대체
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff 버전은 설치된 버전과 맞추는 것이 좋습니다.
    rev: v0.14.9
    hooks:
      - id: ruff
        args: [ --fix ]  # 자동 수정 기능 활성화