# Generated by Django 5.2.10 on 2026-03-26 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("input_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Simulation ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated unique code (SMYYYYMMDD_NNN)",
                        max_length=20,
                        unique=True,
                        verbose_name="Simulation Code",
                    ),
                ),
                (
                    "simulation_status",
                    models.CharField(default="SNAPSHOTTING", max_length=20),
                ),
                ("progress", models.IntegerField(default=0, help_text="진행률 (%)")),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery Task ID (비동기 작업 추적용)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "solver_type",
                    models.CharField(
                        default="OR-Tools", help_text="Solver 유형", max_length=50
                    ),
                ),
                ("model_start_time", models.DateTimeField(blank=True, null=True)),
                ("model_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "model_status",
                    models.CharField(
                        blank=True, help_text="모델 실행 상태", max_length=50, null=True
                    ),
                ),
                ("objective_value", models.FloatField(blank=True, null=True)),
                (
                    "execution_time",
                    models.FloatField(
                        blank=True, help_text="실행 시간 (초)", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this Simulation tests",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for categorization (e.g., capacity-test, route-optimization)",
                        max_length=200,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="input_data.scenarioinfo",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation Execution",
                "verbose_name_plural": "Simulation Execution",
                "db_table": "simulation_run",
                "ordering": ["-created_at"],
            },
        ),
    ]
