# Generated by Django 5.2.10 on 2026-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationrun",
            name="tags",
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="algorithm_type",
            field=models.CharField(
                choices=[
                    ("EXACT", "MIP"),
                    ("EFFICIENT", "Metaheuristic"),
                    ("FAST", "Greedy / Rule-based"),
                ],
                default="EXACT",
                max_length=20,
                verbose_name="Search Type",
            ),
        ),
        migrations.AlterField(
            model_name="simulationrun",
            name="solver_type",
            field=models.CharField(
                default="cplex", max_length=20, verbose_name="Solver Type"
            ),
        ),
    ]
