# Generated by Django 5.2.10 on 2026-04-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0002_remove_simulationrun_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationrun",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated tags for categorization (e.g., capacity-test, route-optimization)",
                max_length=200,
                verbose_name="Tags",
            ),
        ),
    ]
