# Generated by Django 5.2.10 on 2026-04-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0003_simulationrun_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationrun",
            name="tags",
        ),
    ]
