"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 시스템 환경변수 'APP_ENV'가 'docker'이면 .env.docker를, 아니면 .env.local을 읽습니다.
APP_ENV = os.environ.get("APP_ENV", "local")
if APP_ENV == "docker":
    env_path = BASE_DIR / ".env.docker"
    print(f"[DOCKER] Loading environment: ({env_path})")
else:
    env_path = BASE_DIR / ".env.local"
    print(f"[LOCAL] Loading environment: ({env_path})")

load_dotenv(env_path)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "insecure-default-key")

# [중요] 배포 시에는 False여야 합니다. (.env에서 관리 권장)
DEBUG = os.getenv("DEBUG", "False").lower() == "true"
# [중요] 서버의 도메인이나 IP를 반드시 추가해야 합니다.
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# 사용자가 업로드한 파일(엑셀 등)을 저장하고 서빙하는 경로
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# HTML 템플릿에서 {% static 'css/style.css' %}를 쓰면 /static/css/style.css로 변환해주는 역할
STATIC_URL = "/static/"
# 개발 중에 프로젝트 최상위 static 폴더를 정적 파일 검색 대상에 추가
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 여기에 프로젝트 루트의 static/ 폴더 경로
]
# 배포 시에 collectstatic 명령어로 모아지는 폴더
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",  # api 구축용
    "drf_spectacular",  # API 문서 자동 생성 도구
    "simple_history",  # audit logging
    # Custom Apps
    "common",
    "input_data.apps.InputDataConfig",
    "simulation",  # 시뮬레이션 앱 추가
    "api",
]
if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # SessionMiddleware 이후에 와야 request.user가 세팅 가능
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # AuthenticationMiddleware 이후에 와야 request.user에 접근 가능
    "simple_history.middleware.HistoryRequestMiddleware",
]
if DEBUG:
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "common.context_processors.global_menus",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "postgres"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}
# 테스트용 데이터베이스 (pytest / CI)
DATABASES["default"]["TEST"] = {
    "NAME": os.getenv("DB_TEST_NAME", DATABASES["default"]["NAME"])
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# 로그 디렉토리 생성 (없으면)
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# Authentication Settings
LOGIN_REDIRECT_URL = "/input/"  # 로그인 후 메인 페이지로 이동
LOGOUT_REDIRECT_URL = "/accounts/login/"  # 로그아웃 후 로그인 페이지로 이동

# ==========================================
# Data Source Configuration
# ==========================================

# Default to 'DB' if not set. .upper() ensures 'db' and 'DB' work the same.
DATA_SOURCE_TYPE = os.environ.get("DATA_SOURCE_TYPE", "DB").upper()

API_URL = os.environ.get("API_URL", "")
API_KEY = os.environ.get("API_KEY", "")

SIMULATION_ENGINE_API_URL = os.environ.get("SIMULATION_ENGINE_API_URL", API_URL)
SIMULATION_ENGINE_API_KEY = os.environ.get("SIMULATION_ENGINE_API_KEY", API_KEY)
SIMULATION_ENGINE_TIMEOUT = int(os.environ.get("SIMULATION_ENGINE_TIMEOUT", 30))

SCENARIO_DATA_API_URL = os.environ.get(
    "SCENARIO_DATA_API_URL",
    f"{API_URL}/scenario-data" if API_URL else "",
)
SCENARIO_DATA_API_KEY = os.environ.get("SCENARIO_DATA_API_KEY", API_KEY)
SCENARIO_DATA_API_TIMEOUT = int(
    os.environ.get("SCENARIO_DATA_API_TIMEOUT", SIMULATION_ENGINE_TIMEOUT)
)

# Simple validation warning
if DATA_SOURCE_TYPE == "API" and not API_URL:
    print("WARNING: DATA_SOURCE_TYPE is set to 'API', but API_URL is missing.")

# ==============================================================================
# Celery Configuration
# ==============================================================================
# [환경별 Celery 동작 모드 설정]
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    "redis://redis:6379/0" if APP_ENV == "docker" else "",
)
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    "redis://redis:6379/0" if APP_ENV == "docker" else "",
)

if CELERY_BROKER_URL and CELERY_RESULT_BACKEND:
    # 브로커/백엔드가 명시되면 실제 비동기 실행
    CELERY_TASK_ALWAYS_EAGER = False
else:
    # 미설정 시에는 eager 모드로 동작해 로컬 디버깅 편의 유지
    print("[LOCAL] Celery running in EAGER mode (Synchronous)")
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"

# 작업 결과 유지 시간 (초)
CELERY_RESULT_EXPIRES = 3600

# Content Type 허용 (보안)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# 타임존 설정 (Django TIME_ZONE 사용)
CELERY_TIMEZONE = TIME_ZONE

# =========================================================
# [HTTPS 환경 설정]
# Docker(Nginx+SSL) 환경에서만 보안 쿠키·리다이렉트를 활성화합니다.
# 로컬 개발(http://localhost)에서는 비활성화해야 로그인이 정상 동작합니다.
# =========================================================
if APP_ENV == "docker":
    # 1. 쿠키 보안 활성화
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # 2. SSL 리다이렉트 (Nginx가 이미 301 리다이렉트를 하므로 False 권장)
    SECURE_SSL_REDIRECT = False
    # 3. CSRF 신뢰할 수 있는 출처
    CSRF_TRUSTED_ORIGINS = [
        "https://localhost",
        "https://127.0.0.1",
        "https://opusopt-demo.com",
        "https://192.168.0.15",
    ]
else:
    # 로컬 개발: HTTP 전용
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost",
        "http://127.0.0.1",
    ]

# 가장 빠른 비밀번호 해시 알고리즘 사용 (테스트 속도 대폭 향상)
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.MD5PasswordHasher",
]
